[package]
name = "chip8-emu-rust"
version = "0.1.0"
authors = ["septa97"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
sdl2 = "0.34"